from src.config import variable_names
from src.core.base_model import Model


def calculate_return_on_advertising_spend(optional_variables: dict, **kwargs) -> dict:
    """
    Calculates the Return on Advertising Spend (ROAS) metric for marketing performance tracking.

    Mathematical Formula:
        ROAS = Revenue / AdvertisingCost

    Args:
        optional_variables (dict): Mapped configuration containing default parameter fallbacks.
        **kwargs: Arbitrary keyword arguments containing the required calculation
            metrics extracted from the model's global configuration variables.

            Mandatory Keys:
                REVENUE (float): Total gross top-line revenue generated by sales transactions.
                ADVERTISING_COST (float): Total financial capital spent across ad campaigns.

            Optional Keys:
                None.

    Returns:
        dict: A dictionary containing the computed Return on Advertising Spend (ROAS),
            mapped directly to the global configuration constant name.
            Example: {"ROAS": 4.50} (meaning 4.5x return or 450%)
    """
    # Extract structural required fields (will throw KeyError if missing, as intended)
    revenue = kwargs[variable_names.REVENUE]
    advertising_cost = kwargs[variable_names.ADVERTISING_COST]

    # Cleaned up the local variable name to reflect ROAS rather than profit
    calculated_roas = revenue / advertising_cost

    return {variable_names.ROAS: calculated_roas}


class RoasModel(Model):
    """
    Pipeline calculation block evaluating top-line capital returns against total marketing spend.

    Description:
        This model evaluates high-level marketing efficiency by mapping gross revenue output
        directly against top-of-funnel advertising expenditures. Under the current baseline assumption,
        all revenue is attributed to ad-driven performance channels. The resulting metric serves
        as an immediate benchmark for campaign viability and scaling efficiency.

    Calculation Equation:
        ROAS = Revenue / AdvertisingCost

        Where:
        - "Revenue" maps to variable_names.REVENUE
        - "AdvertisingCost" maps to variable_names.ADVERTISING_COST
    """

    def __init__(self, input_variables: dict = None):
        """
        Initializes the ReturnOnAdvertisingSpendModel with defined tracking boundaries.

        Args:
            input_variables (dict, optional): The active runtime configuration context dictionary
                containing variables and metrics (e.g., {variable_names.REVENUE: 10000.0}).
                If None, it defaults securely to an empty dictionary via the parent class.
        """
        super().__init__(input_variables)

        # Binding calculation identity and specifying the explicit output registry signature
        self._model_function = calculate_return_on_advertising_spend
        self._output_names = [variable_names.ROAS]

        # Enforcing configuration dependency boundaries
        self._required_variables = [
            variable_names.REVENUE,
            variable_names.ADVERTISING_COST
        ]
