from src.utils import log


def evaluate_chained_models(runtime_state: dict, model_pipeline: list) -> dict:
    """
    Executes a sequential calculation cascade across a pipeline of pre-instantiated models.

    This function serves as the central orchestration engine for LedgerScope's model 
    execution pipeline. It processes an ordered sequence of live model objects, allowing 
    downstream models to naturally consume, transform, or append to calculations generated 
    by upstream stages.

    To isolate executions and prevent state pollution across multi-run scenarios (such 
    as sensitivity matrix sweeps), all mutations are confined to a shallow-copied runtime 
    state dictionary.

    Args:
        runtime_state (dict): A baseline dictionary containing primitive input metrics,
            financial parameters, or environmental configurations.
        model_pipeline (list): An ordered sequence of pre-configured, instantiated 
            model objects, each implementing an `.evaluate()` execution method.

    Returns:
        dict: An accumulated state dictionary containing all baseline inputs merged 
            with the key-value calculation outputs generated by every executed pipeline stage.

    Raises:
        Exception: Re-raises any execution runtime error encountered inside a model's
            `.evaluate()` block, capturing the specific failing class identifier in the logs.
    """
    # Isolate runtime state to ensure pure, idempotent simulation runs
    current_state = dict(runtime_state)

    for model in model_pipeline:
        # Dynamically extract the identifier string directly from the live object
        model_name = model.__class__.__name__

        try:
            model.input_variables = current_state
            model.evaluate()
        except Exception as error:
            log.error(f"Unexpected operational crash inside execution block [{model_name}]: {error}")
            raise error

    return current_state
