from matplotlib import cm

from src.config import plots

# Color Palette Mapping Strategy
REGRESSION_COLORMAP = cm.viridis_r
GRID_LINE_COLOR = '#dee2e6'
SPINE_BORDER_COLOR = '#dee2e6'

# Structural Element Formats
TREND_LINE_PROPERTIES = plots.LINEAR_REGRESSION_LINE_FORMAT
DATA_POINT_PROPERTIES = plots.LINEAR_REGRESSION_POINT_STYLE

# Font Sizing Rules Mapping
TITLE_FONT_CONFIGURATION = plots.TITLE_FONT
X_AXIS_LABEL_FONT = plots.LINEAR_REGRESSION_X_AXIS_FONT
Y_AXIS_LABEL_FONT = plots.LINEAR_REGRESSION_Y_AXIS_FONT
IN_LEGEND_TEXT_FONTS = plots.LINEAR_REGRESSION_IN_LEGENDS_TEXT_FONTS

# Positional and Padding Settings
Y_AXIS_LABEL_PAD = 35
Y_AXIS_LABEL_ROTATION = 0
Y_AXIS_LABEL_Y_CENTER = 0.5
X_AXIS_TICK_ROTATION = 45

# Sizing Constraints
CANVAS_FIGURE_SIZE = plots.LINEAR_REGRESSION_FIGURE_SIZE
POINT_SIZE_MINIMUM = plots.LINEAR_REGRESSION_POINT_SIZE_MIN
POINT_SIZE_MAXIMUM = plots.LINEAR_REGRESSION_POINT_SIZE_MAX
X_AXIS_TICK_SIZE = plots.LINEAR_REGRESSION_TICK_SIZE
Y_AXIS_TICK_SIZE = plots.LINEAR_REGRESSION_TICK_SIZE

# Functional Strings
CANVAS_MAIN_TITLE = plots.LINEAR_REGRESSION_TITLE
GOAL_BENCHMARK_TEMPLATE = plots.LINEAR_REGRESSION_LINE_GOAL
X_AXIS_COLOR_RULE = plots.X_AXIS_COLOR
Y_AXIS_COLOR_RULE = plots.Y_AXIS_COLOR
