from src.config import variable_names
from src.core.base_model import Model


def calculate_orders(optional_variables: dict, **kwargs) -> dict:
    """
    Calculates total finalized sales transactions converted from acquired top-of-funnel leads.

    Mathematical Formula:
        Orders = Leads * CloseRate

    Description:
        This function represents the bottom-of-funnel conversion engine. It takes the gross
        volume of prospect leads generated by marketing channels and scales them by the
        sales team's closing efficiency rate to estimate actual realized business transactions.

    Args:
        optional_variables (dict): Mapped configuration containing default parameter fallbacks.
        **kwargs: Arbitrary keyword arguments containing required calculation metrics:

            Mandatory Keys:
                LEADS (float or int): Total prospect leads acquired from upstream acquisition channels.
                CLOSE_RATE (float): The fractional sales pipeline conversion efficiency (0.0 to 1.0).

    Returns:
        dict: A dictionary mapping the calculated order volume directly to the operational registry.
            Example: {"Orders": 64.8}
    """
    # Extract structural required fields (will throw KeyError if missing, as intended)
    leads = kwargs[variable_names.LEADS]
    close_rate = kwargs[variable_names.CLOSE_RATE]

    calculated_orders = leads * close_rate

    return {variable_names.DEAL_ORDERS: calculated_orders}


class OrderModel(Model):
    """
    Pipeline calculation block responsible for converting top-of-funnel prospect
    Leads into finalized transactional Orders.

    Description:
        This model serves as the connective tissue between marketing discovery and revenue
        realization within the business lifecycle pipeline. By taking the output of upstream
        lead generation layers and applying a sales closing percentage metric, it establishes
        the ultimate transaction volume driver used down-funnel for fulfillment cost calculations,
        gross revenue profiling, and inventory planning.

    Calculation Equation:
        orders = total acquired leads * pipeline close rate

        Where:
        - "total acquired leads" maps to LEADS
        - "pipeline close rate" maps to CLOSE_RATE
    """

    def __init__(self, input_variables: dict = None):
        """
        Initializes the OrderModel with explicit parameter validation boundaries.

        Args:
            input_variables (dict, optional): The active runtime configuration context dictionary.
                If None, it defaults securely to an empty dictionary via the parent class.
        """
        super().__init__(input_variables)

        # Binding calculation identity and specifying the explicit output registry signature
        self._model_function = calculate_orders
        self._output_names = [variable_names.DEAL_ORDERS]

        # Enforcing configuration dependency boundaries
        self._required_variables = [
            variable_names.LEADS,
            variable_names.CLOSE_RATE
        ]
