import unittest

from src.analysis import run_monte_carlo
from src.config import variable_names
from src.core import Variable
from src.models import NetIncomeModel, MarketPriceModel
from src.variables import PriceToEarningsRatio


def _create_var(min_v, exp_v, max_v):
    return Variable(min=min_v, exp=exp_v, max=max_v)


class TestMonteCarloIntegration(unittest.TestCase):

    def setUp(self):
        """Build fiscal pipeline for simulation."""
        self.pipeline = [NetIncomeModel(), MarketPriceModel()]

        self.variables = {
            variable_names.REVENUE: _create_var(80000.0, 100000.0, 120000.0),
            variable_names.COST: _create_var(30000.0, 40000.0, 50000.0),
            variable_names.PE_RATIO: PriceToEarningsRatio(min=5.0, exp=8.0, max=10.0)
        }

    # -----------------------------------------------------------------
    # 1. ACCURACY: ITERATION & TRACKING
    # -----------------------------------------------------------------

    def test_run_monte_carlo_execution_completes_requested_iterations(self):
        """Verify that the simulation executes for the exact requested iteration count."""
        results = run_monte_carlo(
            variables=self.variables,
            shuffled_inputs=[variable_names.REVENUE],
            model_pipeline=self.pipeline,
            iterations=50
        )
        self.assertEqual(len(results), 50)
        self.assertIn(variable_names.SYSTEM_RUN_ID, results[0])

    def test_run_monte_carlo_captures_only_tracked_outputs(self):
        """Verify that result dictionaries contain only the explicitly requested metrics."""
        results = run_monte_carlo(
            variables=self.variables,
            shuffled_inputs=[variable_names.REVENUE],
            model_pipeline=self.pipeline,
            tracked_outputs=[variable_names.MARKET_PRICE],
            iterations=10
        )
        # Should contain tracked output + internal ID
        self.assertEqual(set(results[0].keys()), {variable_names.MARKET_PRICE, variable_names.SYSTEM_RUN_ID})

    # -----------------------------------------------------------------
    # 2. RESILIENCE: GUARDRAILS & ERROR HANDLING
    # -----------------------------------------------------------------

    def test_run_monte_carlo_aborts_on_missing_registry_shuffled_input(self):
        """Verify registry guardrail raises KeyError when requested shuffled input is absent."""
        with self.assertRaises(KeyError):
            run_monte_carlo(
                variables=self.variables,
                shuffled_inputs=["UNDEFINED_INPUT"],
                model_pipeline=self.pipeline
            )

    def test_run_monte_carlo_aborts_on_missing_registry_mandatory_input(self):
        """Verify registry guardrail raises KeyError when mandatory input (COST) is absent."""
        invalid_variables = {
            variable_names.REVENUE: self.variables[variable_names.REVENUE],
            variable_names.PE_RATIO: self.variables[variable_names.PE_RATIO]
        }
        with self.assertRaises(KeyError):
            run_monte_carlo(
                variables=invalid_variables,
                shuffled_inputs=[variable_names.REVENUE],
                model_pipeline=self.pipeline
            )

    def test_run_monte_carlo_aborts_on_invalid_pipeline_topology(self):
        """Verify topology guardrail raises KeyError when model order violates lineage."""
        broken_pipeline = [MarketPriceModel(), NetIncomeModel()]
        with self.assertRaises(KeyError) as cm:
            run_monte_carlo(
                variables=self.variables,
                shuffled_inputs=[variable_names.REVENUE],
                model_pipeline=broken_pipeline
            )
        self.assertIn("Pipeline Order Violation", str(cm.exception))

    def test_run_monte_carlo_aborts_on_invalid_tracked_output(self):
        """Ensure KeyError is raised if a requested tracked output is not generated by the pipeline."""
        with self.assertRaises(KeyError):
            run_monte_carlo(
                variables=self.variables,
                shuffled_inputs=[variable_names.REVENUE],
                model_pipeline=self.pipeline,
                tracked_outputs=["NON_EXISTENT_METRIC"]
            )


if __name__ == "__main__":
    unittest.main()
